source_file: tradesy_images_paths.csv
id_each_content:
- itemID
exogenous_representations: null
field_representations:
  image_path/0:
    PytorchImageModels:
      model_name: vgg19
      feature_layer: features
      flatten: true
      device: cuda:0
      apply_on_output: <function content_analyzer.<locals>.pool_and_squeeze at 0x0000028C7FD6F820>
      imgs_dirs: C:\Users\eliom\Desktop\VBPR-Replicability-src\data\interim\imgs_dirs
      max_timeout: 2
      max_retries: 5
      max_workers: 0
      batch_size: 32
      resize_size:
      - 256
      - 256
    preprocessing:
      CenterCrop:
        size:
        - 224
        - 224
      Normalize:
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
  image_path/1:
    PytorchImageModels:
      model_name: resnet50
      feature_layer: global_pool
      flatten: true
      device: cuda:0
      apply_on_output: null
      imgs_dirs: C:\Users\eliom\Desktop\VBPR-Replicability-src\data\interim\imgs_dirs
      max_timeout: 2
      max_retries: 5
      max_workers: 0
      batch_size: 32
      resize_size:
      - 256
      - 256
    preprocessing:
      CenterCrop:
        size:
        - 224
        - 224
      Normalize:
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
  image_path/2:
    CaffeImageModels:
      prototxt_path: C:\Users\eliom\Desktop\VBPR-Replicability-src\models\reference_caffenet\deploy.prototxt
      model_path: C:\Users\eliom\Desktop\VBPR-Replicability-src\models\reference_caffenet\bvlc_reference_caffenet.caffemodel
      feature_layer: relu7
      mean_file_path: C:\Users\eliom\Desktop\VBPR-Replicability-src\models\reference_caffenet\ilsvrc_2012_mean.npy
      swap_rb: true
      flatten: true
      imgs_dirs: C:\Users\eliom\Desktop\VBPR-Replicability-src\data\interim\imgs_dirs
      use_gpu: false
      max_timeout: 2
      max_retries: 5
      max_workers: 0
      batch_size: 512
      resize_size:
      - 227
      - 227
    preprocessing:
      Lambda: {}
  image_path/3:
    CaffeImageModels:
      prototxt_path: C:\Users\eliom\Desktop\VBPR-Replicability-src\models\reference_caffenet\deploy.prototxt
      model_path: C:\Users\eliom\Desktop\VBPR-Replicability-src\models\reference_caffenet\bvlc_reference_caffenet.caffemodel
      feature_layer: relu7
      mean_file_path: null
      swap_rb: false
      flatten: true
      imgs_dirs: C:\Users\eliom\Desktop\VBPR-Replicability-src\data\interim\imgs_dirs
      use_gpu: false
      max_timeout: 2
      max_retries: 5
      max_workers: 0
      batch_size: 512
      resize_size:
      - 300
      - 300
    preprocessing:
      CenterCrop:
        size:
        - 227
        - 227
      Lambda: {}
