name: Linting src package
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: XXXX-10
        with:
          package-path: src
          python-version: 3.9
          requirements-path: requirements.txt
          readme-path: README.md
